### ISSUE TITLE
Switch to dcos.io CloudFormation templates

### ISSUE THREAD

**Issue by mlafeldt** [dcos-labs/dcos-bootstrap#4]
Which are linked at https://downloads.dcos.io/dcos/EarlyAccess/aws.html

**Comment by mlafeldt** [comment]
@mhausenblas I've got a couple of questions. :)
1. It looks like there are no "stable" releases for open source DC/OS anymore (only "EarlyAccess")? Is this going to stay that way?
2. The last release seems to be relatively old:
   
   ```
   DC/OS Release: CM.7
   DC/OS Commit: 14509fe1e7899f439527fb39867194c7a425c771
   ```
   
   I'd like to know what the release process looks like? (To be honest, I still haven't figured out how https://github.com/dcos/dcos/tree/master/gen/aws is used to generate the template.)
3. The "old" templates under https://s3.amazonaws.com/downloads.mesosphere.io/dcos still exist. Is this for Enterprise DC/OS only now? Or is it a leftover which will be removed at some point?

**Comment by mhausenblas** [comment]
Hmm, not sure if I'm following @mlafeldt — is https://dcos.io/releases/ not clear? :)

**Comment by mlafeldt** [comment]
Never mind, didn't know about that page. :)

**Comment by mhausenblas** [comment]
Well hidden at the bottom of each dcos.io page. Seems we did an excellent job in terms of anti-discovery 🎯

**Comment by mlafeldt** [comment]
One more thing regarding the templates on S3.

This works:

https://s3.amazonaws.com/downloads.mesosphere.io/dcos/EarlyAccess/cloudformation/single-master.cloudformation.json

But this doesn't:

https://s3.amazonaws.com/downloads.dcos.io/dcos/EarlyAccess/cloudformation/single-master.cloudformation.json

(error: `The bucket you are attempting to access must be addressed using the specified endpoint.`)

Instead, one has to define a specific S3 region (us-west-2):

https://s3-us-west-2.amazonaws.com/downloads.dcos.io/dcos/EarlyAccess/cloudformation/single-master.cloudformation.json

(Not a real problem.)
